package com.mycompany.microservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AdditionalInformationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdditionalInformationAllPropertiesEquals(AdditionalInformation expected, AdditionalInformation actual) {
        assertAdditionalInformationAutoGeneratedPropertiesEquals(expected, actual);
        assertAdditionalInformationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdditionalInformationAllUpdatablePropertiesEquals(
        AdditionalInformation expected,
        AdditionalInformation actual
    ) {
        assertAdditionalInformationUpdatableFieldsEquals(expected, actual);
        assertAdditionalInformationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdditionalInformationAutoGeneratedPropertiesEquals(
        AdditionalInformation expected,
        AdditionalInformation actual
    ) {
        assertThat(actual)
            .as("Verify AdditionalInformation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdditionalInformationUpdatableFieldsEquals(AdditionalInformation expected, AdditionalInformation actual) {
        assertThat(actual)
            .as("Verify AdditionalInformation relevant properties")
            .satisfies(a -> assertThat(a.getSmoking()).as("check smoking").isEqualTo(expected.getSmoking()))
            .satisfies(a -> assertThat(a.getAlcoholRiskLevel()).as("check alcoholRiskLevel").isEqualTo(expected.getAlcoholRiskLevel()))
            .satisfies(a ->
                assertThat(a.getAlcoholGlassesPerDay()).as("check alcoholGlassesPerDay").isEqualTo(expected.getAlcoholGlassesPerDay())
            )
            .satisfies(a -> assertThat(a.getDrugUse()).as("check drugUse").isEqualTo(expected.getDrugUse()))
            .satisfies(a -> assertThat(a.getPhysicalActivity()).as("check physicalActivity").isEqualTo(expected.getPhysicalActivity()))
            .satisfies(a -> assertThat(a.getExposureFactor()).as("check exposureFactor").isEqualTo(expected.getExposureFactor()))
            .satisfies(a -> assertThat(a.getExposureDate()).as("check exposureDate").isEqualTo(expected.getExposureDate()))
            .satisfies(a -> assertThat(a.getTypeToilet()).as("check typeToilet").isEqualTo(expected.getTypeToilet()))
            .satisfies(a -> assertThat(a.getEnvironmentalRisk()).as("check environmentalRisk").isEqualTo(expected.getEnvironmentalRisk()))
            .satisfies(a ->
                assertThat(a.getCardiovascularDisease()).as("check cardiovascularDisease").isEqualTo(expected.getCardiovascularDisease())
            )
            .satisfies(a -> assertThat(a.getHypertension()).as("check hypertension").isEqualTo(expected.getHypertension()))
            .satisfies(a -> assertThat(a.getDiabetes()).as("check diabetes").isEqualTo(expected.getDiabetes()))
            .satisfies(a -> assertThat(a.getStomachDisease()).as("check stomachDisease").isEqualTo(expected.getStomachDisease()))
            .satisfies(a -> assertThat(a.getChronicLungDisease()).as("check chronicLungDisease").isEqualTo(expected.getChronicLungDisease())
            )
            .satisfies(a -> assertThat(a.getAsthma()).as("check asthma").isEqualTo(expected.getAsthma()))
            .satisfies(a -> assertThat(a.getGoiter()).as("check goiter").isEqualTo(expected.getGoiter()))
            .satisfies(a -> assertThat(a.getHepatitis()).as("check hepatitis").isEqualTo(expected.getHepatitis()))
            .satisfies(a ->
                assertThat(a.getCongenitalHeartDisease()).as("check congenitalHeartDisease").isEqualTo(expected.getCongenitalHeartDisease())
            )
            .satisfies(a -> assertThat(a.getMentalDisorders()).as("check mentalDisorders").isEqualTo(expected.getMentalDisorders()))
            .satisfies(a -> assertThat(a.getAutism()).as("check autism").isEqualTo(expected.getAutism()))
            .satisfies(a -> assertThat(a.getEpilepsy()).as("check epilepsy").isEqualTo(expected.getEpilepsy()))
            .satisfies(a -> assertThat(a.getCancer()).as("check cancer").isEqualTo(expected.getCancer()))
            .satisfies(a -> assertThat(a.getTuberculosis()).as("check tuberculosis").isEqualTo(expected.getTuberculosis()))
            .satisfies(a -> assertThat(a.getOtherDiseases()).as("check otherDiseases").isEqualTo(expected.getOtherDiseases()))
            .satisfies(a ->
                assertThat(a.getContraceptiveMethod()).as("check contraceptiveMethod").isEqualTo(expected.getContraceptiveMethod())
            )
            .satisfies(a -> assertThat(a.getLastPregnancy()).as("check lastPregnancy").isEqualTo(expected.getLastPregnancy()))
            .satisfies(a ->
                assertThat(a.getNumberOfPregnancies()).as("check numberOfPregnancies").isEqualTo(expected.getNumberOfPregnancies())
            )
            .satisfies(a ->
                assertThat(a.getNumberOfMiscarriages()).as("check numberOfMiscarriages").isEqualTo(expected.getNumberOfMiscarriages())
            )
            .satisfies(a -> assertThat(a.getNumberOfAbortions()).as("check numberOfAbortions").isEqualTo(expected.getNumberOfAbortions()))
            .satisfies(a -> assertThat(a.getNumberOfBirths()).as("check numberOfBirths").isEqualTo(expected.getNumberOfBirths()))
            .satisfies(a -> assertThat(a.getVaginalDelivery()).as("check vaginalDelivery").isEqualTo(expected.getVaginalDelivery()))
            .satisfies(a -> assertThat(a.getCesareanSection()).as("check cesareanSection").isEqualTo(expected.getCesareanSection()))
            .satisfies(a -> assertThat(a.getDifficultDelivery()).as("check difficultDelivery").isEqualTo(expected.getDifficultDelivery()))
            .satisfies(a ->
                assertThat(a.getNumberOfFullTermBirths()).as("check numberOfFullTermBirths").isEqualTo(expected.getNumberOfFullTermBirths())
            )
            .satisfies(a ->
                assertThat(a.getNumberOfPrematureBirths())
                    .as("check numberOfPrematureBirths")
                    .isEqualTo(expected.getNumberOfPrematureBirths())
            )
            .satisfies(a ->
                assertThat(a.getNumberOfChildrenAlive()).as("check numberOfChildrenAlive").isEqualTo(expected.getNumberOfChildrenAlive())
            )
            .satisfies(a ->
                assertThat(a.getGynecologicalDiseases()).as("check gynecologicalDiseases").isEqualTo(expected.getGynecologicalDiseases())
            )
            .satisfies(a -> assertThat(a.getBirthStatus()).as("check birthStatus").isEqualTo(expected.getBirthStatus()))
            .satisfies(a -> assertThat(a.getBirthWeight()).as("check birthWeight").isEqualTo(expected.getBirthWeight()))
            .satisfies(a -> assertThat(a.getBirthHeight()).as("check birthHeight").isEqualTo(expected.getBirthHeight()))
            .satisfies(a -> assertThat(a.getBirthDefectNote()).as("check birthDefectNote").isEqualTo(expected.getBirthDefectNote()))
            .satisfies(a -> assertThat(a.getOtherBirthNote()).as("check otherBirthNote").isEqualTo(expected.getOtherBirthNote()))
            .satisfies(a -> assertThat(a.getOtherHealthNote()).as("check otherHealthNote").isEqualTo(expected.getOtherHealthNote()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdditionalInformationUpdatableRelationshipsEquals(
        AdditionalInformation expected,
        AdditionalInformation actual
    ) {
        // empty method
    }
}
