package com.mycompany.microservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AllergyAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAllergyAllPropertiesEquals(Allergy expected, Allergy actual) {
        assertAllergyAutoGeneratedPropertiesEquals(expected, actual);
        assertAllergyAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAllergyAllUpdatablePropertiesEquals(Allergy expected, Allergy actual) {
        assertAllergyUpdatableFieldsEquals(expected, actual);
        assertAllergyUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAllergyAutoGeneratedPropertiesEquals(Allergy expected, Allergy actual) {
        assertThat(actual)
            .as("Verify Allergy auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAllergyUpdatableFieldsEquals(Allergy expected, Allergy actual) {
        assertThat(actual)
            .as("Verify Allergy relevant properties")
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAllergyUpdatableRelationshipsEquals(Allergy expected, Allergy actual) {
        assertThat(actual)
            .as("Verify Allergy relationships")
            .satisfies(a -> assertThat(a.getPatient()).as("check patient").isEqualTo(expected.getPatient()));
    }
}
