package com.mycompany.microservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DisabilityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisabilityAllPropertiesEquals(Disability expected, Disability actual) {
        assertDisabilityAutoGeneratedPropertiesEquals(expected, actual);
        assertDisabilityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisabilityAllUpdatablePropertiesEquals(Disability expected, Disability actual) {
        assertDisabilityUpdatableFieldsEquals(expected, actual);
        assertDisabilityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisabilityAutoGeneratedPropertiesEquals(Disability expected, Disability actual) {
        assertThat(actual)
            .as("Verify Disability auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisabilityUpdatableFieldsEquals(Disability expected, Disability actual) {
        assertThat(actual)
            .as("Verify Disability relevant properties")
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisabilityUpdatableRelationshipsEquals(Disability expected, Disability actual) {
        assertThat(actual)
            .as("Verify Disability relationships")
            .satisfies(a -> assertThat(a.getPatient()).as("check patient").isEqualTo(expected.getPatient()));
    }
}
