package com.mycompany.microservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FamilyAllergyAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilyAllergyAllPropertiesEquals(FamilyAllergy expected, FamilyAllergy actual) {
        assertFamilyAllergyAutoGeneratedPropertiesEquals(expected, actual);
        assertFamilyAllergyAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilyAllergyAllUpdatablePropertiesEquals(FamilyAllergy expected, FamilyAllergy actual) {
        assertFamilyAllergyUpdatableFieldsEquals(expected, actual);
        assertFamilyAllergyUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilyAllergyAutoGeneratedPropertiesEquals(FamilyAllergy expected, FamilyAllergy actual) {
        assertThat(actual)
            .as("Verify FamilyAllergy auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilyAllergyUpdatableFieldsEquals(FamilyAllergy expected, FamilyAllergy actual) {
        assertThat(actual)
            .as("Verify FamilyAllergy relevant properties")
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getAffectedPerson()).as("check affectedPerson").isEqualTo(expected.getAffectedPerson()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilyAllergyUpdatableRelationshipsEquals(FamilyAllergy expected, FamilyAllergy actual) {
        assertThat(actual)
            .as("Verify FamilyAllergy relationships")
            .satisfies(a -> assertThat(a.getPatient()).as("check patient").isEqualTo(expected.getPatient()));
    }
}
