package com.mycompany.microservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FamilyDiseaseAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilyDiseaseAllPropertiesEquals(FamilyDisease expected, FamilyDisease actual) {
        assertFamilyDiseaseAutoGeneratedPropertiesEquals(expected, actual);
        assertFamilyDiseaseAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilyDiseaseAllUpdatablePropertiesEquals(FamilyDisease expected, FamilyDisease actual) {
        assertFamilyDiseaseUpdatableFieldsEquals(expected, actual);
        assertFamilyDiseaseUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilyDiseaseAutoGeneratedPropertiesEquals(FamilyDisease expected, FamilyDisease actual) {
        assertThat(actual)
            .as("Verify FamilyDisease auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilyDiseaseUpdatableFieldsEquals(FamilyDisease expected, FamilyDisease actual) {
        assertThat(actual)
            .as("Verify FamilyDisease relevant properties")
            .satisfies(a -> assertThat(a.getAffectedPerson()).as("check affectedPerson").isEqualTo(expected.getAffectedPerson()))
            .satisfies(a ->
                assertThat(a.getRelationshipToPatient()).as("check relationshipToPatient").isEqualTo(expected.getRelationshipToPatient())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilyDiseaseUpdatableRelationshipsEquals(FamilyDisease expected, FamilyDisease actual) {
        assertThat(actual)
            .as("Verify FamilyDisease relationships")
            .satisfies(a -> assertThat(a.getPatient()).as("check patient").isEqualTo(expected.getPatient()));
    }
}
