package com.mycompany.microservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MedicalRecordAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicalRecordAllPropertiesEquals(MedicalRecord expected, MedicalRecord actual) {
        assertMedicalRecordAutoGeneratedPropertiesEquals(expected, actual);
        assertMedicalRecordAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicalRecordAllUpdatablePropertiesEquals(MedicalRecord expected, MedicalRecord actual) {
        assertMedicalRecordUpdatableFieldsEquals(expected, actual);
        assertMedicalRecordUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicalRecordAutoGeneratedPropertiesEquals(MedicalRecord expected, MedicalRecord actual) {
        assertThat(actual)
            .as("Verify MedicalRecord auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicalRecordUpdatableFieldsEquals(MedicalRecord expected, MedicalRecord actual) {
        assertThat(actual)
            .as("Verify MedicalRecord relevant properties")
            .satisfies(a -> assertThat(a.getExaminationDate()).as("check examinationDate").isEqualTo(expected.getExaminationDate()))
            .satisfies(a -> assertThat(a.getMedicalHistory()).as("check medicalHistory").isEqualTo(expected.getMedicalHistory()))
            .satisfies(a -> assertThat(a.getLeftEyeNoGlass()).as("check leftEyeNoGlass").isEqualTo(expected.getLeftEyeNoGlass()))
            .satisfies(a -> assertThat(a.getRightEyeNoGlass()).as("check rightEyeNoGlass").isEqualTo(expected.getRightEyeNoGlass()))
            .satisfies(a -> assertThat(a.getLeftEyeWithGlass()).as("check leftEyeWithGlass").isEqualTo(expected.getLeftEyeWithGlass()))
            .satisfies(a -> assertThat(a.getRightEyeWithGlass()).as("check rightEyeWithGlass").isEqualTo(expected.getRightEyeWithGlass()))
            .satisfies(a -> assertThat(a.getPulse()).as("check pulse").isEqualTo(expected.getPulse()))
            .satisfies(a -> assertThat(a.getTemperature()).as("check temperature").isEqualTo(expected.getTemperature()))
            .satisfies(a -> assertThat(a.getBloodPressure()).as("check bloodPressure").isEqualTo(expected.getBloodPressure()))
            .satisfies(a -> assertThat(a.getRespiratoryRate()).as("check respiratoryRate").isEqualTo(expected.getRespiratoryRate()))
            .satisfies(a -> assertThat(a.getWeight()).as("check weight").isEqualTo(expected.getWeight()))
            .satisfies(a -> assertThat(a.getHeight()).as("check height").isEqualTo(expected.getHeight()))
            .satisfies(a -> assertThat(a.getBmi()).as("check bmi").isEqualTo(expected.getBmi()))
            .satisfies(a -> assertThat(a.getWaist()).as("check waist").isEqualTo(expected.getWaist()))
            .satisfies(a -> assertThat(a.getSkinMucosa()).as("check skinMucosa").isEqualTo(expected.getSkinMucosa()))
            .satisfies(a -> assertThat(a.getOther()).as("check other").isEqualTo(expected.getOther()))
            .satisfies(a -> assertThat(a.getDiseaseName()).as("check diseaseName").isEqualTo(expected.getDiseaseName()))
            .satisfies(a -> assertThat(a.getDiseaseCode()).as("check diseaseCode").isEqualTo(expected.getDiseaseCode()))
            .satisfies(a -> assertThat(a.getAdvice()).as("check advice").isEqualTo(expected.getAdvice()))
            .satisfies(a -> assertThat(a.getDocterName()).as("check docterName").isEqualTo(expected.getDocterName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicalRecordUpdatableRelationshipsEquals(MedicalRecord expected, MedicalRecord actual) {
        assertThat(actual)
            .as("Verify MedicalRecord relationships")
            .satisfies(a -> assertThat(a.getOrganExamination()).as("check organExamination").isEqualTo(expected.getOrganExamination()))
            .satisfies(a -> assertThat(a.getPatient()).as("check patient").isEqualTo(expected.getPatient()));
    }
}
