package com.mycompany.microservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OrganExaminationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganExaminationAllPropertiesEquals(OrganExamination expected, OrganExamination actual) {
        assertOrganExaminationAutoGeneratedPropertiesEquals(expected, actual);
        assertOrganExaminationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganExaminationAllUpdatablePropertiesEquals(OrganExamination expected, OrganExamination actual) {
        assertOrganExaminationUpdatableFieldsEquals(expected, actual);
        assertOrganExaminationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganExaminationAutoGeneratedPropertiesEquals(OrganExamination expected, OrganExamination actual) {
        assertThat(actual)
            .as("Verify OrganExamination auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganExaminationUpdatableFieldsEquals(OrganExamination expected, OrganExamination actual) {
        assertThat(actual)
            .as("Verify OrganExamination relevant properties")
            .satisfies(a -> assertThat(a.getCardiovascular()).as("check cardiovascular").isEqualTo(expected.getCardiovascular()))
            .satisfies(a -> assertThat(a.getRespiratory()).as("check respiratory").isEqualTo(expected.getRespiratory()))
            .satisfies(a -> assertThat(a.getDigestive()).as("check digestive").isEqualTo(expected.getDigestive()))
            .satisfies(a -> assertThat(a.getUrinary()).as("check urinary").isEqualTo(expected.getUrinary()))
            .satisfies(a -> assertThat(a.getMusculoskeletal()).as("check musculoskeletal").isEqualTo(expected.getMusculoskeletal()))
            .satisfies(a -> assertThat(a.getEndocrine()).as("check endocrine").isEqualTo(expected.getEndocrine()))
            .satisfies(a -> assertThat(a.getNeurological()).as("check neurological").isEqualTo(expected.getNeurological()))
            .satisfies(a -> assertThat(a.getPsychiatric()).as("check psychiatric").isEqualTo(expected.getPsychiatric()))
            .satisfies(a -> assertThat(a.getSurgery()).as("check surgery").isEqualTo(expected.getSurgery()))
            .satisfies(a ->
                assertThat(a.getObstetricsAndGynecology())
                    .as("check obstetricsAndGynecology")
                    .isEqualTo(expected.getObstetricsAndGynecology())
            )
            .satisfies(a -> assertThat(a.getOtolaryngology()).as("check otolaryngology").isEqualTo(expected.getOtolaryngology()))
            .satisfies(a ->
                assertThat(a.getDentistryAndMaxillofacialSurgery())
                    .as("check dentistryAndMaxillofacialSurgery")
                    .isEqualTo(expected.getDentistryAndMaxillofacialSurgery())
            )
            .satisfies(a -> assertThat(a.getEye()).as("check eye").isEqualTo(expected.getEye()))
            .satisfies(a -> assertThat(a.getDermatology()).as("check dermatology").isEqualTo(expected.getDermatology()))
            .satisfies(a -> assertThat(a.getNutrition()).as("check nutrition").isEqualTo(expected.getNutrition()))
            .satisfies(a -> assertThat(a.getExercise()).as("check exercise").isEqualTo(expected.getExercise()))
            .satisfies(a -> assertThat(a.getOther()).as("check other").isEqualTo(expected.getOther()))
            .satisfies(a ->
                assertThat(a.getDevelopmentAssessment()).as("check developmentAssessment").isEqualTo(expected.getDevelopmentAssessment())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganExaminationUpdatableRelationshipsEquals(OrganExamination expected, OrganExamination actual) {
        // empty method
    }
}
