package com.mycompany.microservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ParaclinicalResultAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParaclinicalResultAllPropertiesEquals(ParaclinicalResult expected, ParaclinicalResult actual) {
        assertParaclinicalResultAutoGeneratedPropertiesEquals(expected, actual);
        assertParaclinicalResultAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParaclinicalResultAllUpdatablePropertiesEquals(ParaclinicalResult expected, ParaclinicalResult actual) {
        assertParaclinicalResultUpdatableFieldsEquals(expected, actual);
        assertParaclinicalResultUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParaclinicalResultAutoGeneratedPropertiesEquals(ParaclinicalResult expected, ParaclinicalResult actual) {
        assertThat(actual)
            .as("Verify ParaclinicalResult auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParaclinicalResultUpdatableFieldsEquals(ParaclinicalResult expected, ParaclinicalResult actual) {
        assertThat(actual)
            .as("Verify ParaclinicalResult relevant properties")
            .satisfies(a -> assertThat(a.getTestName()).as("check testName").isEqualTo(expected.getTestName()))
            .satisfies(a -> assertThat(a.getResult()).as("check result").isEqualTo(expected.getResult()))
            .satisfies(a -> assertThat(a.getResultDate()).as("check resultDate").isEqualTo(expected.getResultDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParaclinicalResultUpdatableRelationshipsEquals(ParaclinicalResult expected, ParaclinicalResult actual) {
        assertThat(actual)
            .as("Verify ParaclinicalResult relationships")
            .satisfies(a -> assertThat(a.getMedicalRecord()).as("check medicalRecord").isEqualTo(expected.getMedicalRecord()));
    }
}
