package com.mycompany.microservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PatientAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPatientAllPropertiesEquals(Patient expected, Patient actual) {
        assertPatientAutoGeneratedPropertiesEquals(expected, actual);
        assertPatientAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPatientAllUpdatablePropertiesEquals(Patient expected, Patient actual) {
        assertPatientUpdatableFieldsEquals(expected, actual);
        assertPatientUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPatientAutoGeneratedPropertiesEquals(Patient expected, Patient actual) {
        assertThat(actual)
            .as("Verify Patient auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPatientUpdatableFieldsEquals(Patient expected, Patient actual) {
        assertThat(actual)
            .as("Verify Patient relevant properties")
            .satisfies(a -> assertThat(a.getFullName()).as("check fullName").isEqualTo(expected.getFullName()))
            .satisfies(a -> assertThat(a.getGender()).as("check gender").isEqualTo(expected.getGender()))
            .satisfies(a -> assertThat(a.getDateOfBirth()).as("check dateOfBirth").isEqualTo(expected.getDateOfBirth()))
            .satisfies(a -> assertThat(a.getPlaceOfBirth()).as("check placeOfBirth").isEqualTo(expected.getPlaceOfBirth()))
            .satisfies(a -> assertThat(a.getBloodTypeAbo()).as("check bloodTypeAbo").isEqualTo(expected.getBloodTypeAbo()))
            .satisfies(a -> assertThat(a.getBloodTypeRh()).as("check bloodTypeRh").isEqualTo(expected.getBloodTypeRh()))
            .satisfies(a -> assertThat(a.getEthnic()).as("check ethnic").isEqualTo(expected.getEthnic()))
            .satisfies(a -> assertThat(a.getNationality()).as("check nationality").isEqualTo(expected.getNationality()))
            .satisfies(a -> assertThat(a.getReligion()).as("check religion").isEqualTo(expected.getReligion()))
            .satisfies(a -> assertThat(a.getJob()).as("check job").isEqualTo(expected.getJob()))
            .satisfies(a -> assertThat(a.getIdNumber()).as("check idNumber").isEqualTo(expected.getIdNumber()))
            .satisfies(a -> assertThat(a.getIdIssueDate()).as("check idIssueDate").isEqualTo(expected.getIdIssueDate()))
            .satisfies(a -> assertThat(a.getIdIssuePlace()).as("check idIssuePlace").isEqualTo(expected.getIdIssuePlace()))
            .satisfies(a ->
                assertThat(a.getHealthInsuranceNumber()).as("check healthInsuranceNumber").isEqualTo(expected.getHealthInsuranceNumber())
            )
            .satisfies(a -> assertThat(a.getPermanentAddress()).as("check permanentAddress").isEqualTo(expected.getPermanentAddress()))
            .satisfies(a -> assertThat(a.getPermanentWard()).as("check permanentWard").isEqualTo(expected.getPermanentWard()))
            .satisfies(a -> assertThat(a.getPermanentDistrict()).as("check permanentDistrict").isEqualTo(expected.getPermanentDistrict()))
            .satisfies(a -> assertThat(a.getPermanentProvince()).as("check permanentProvince").isEqualTo(expected.getPermanentProvince()))
            .satisfies(a -> assertThat(a.getCurrentAddress()).as("check currentAddress").isEqualTo(expected.getCurrentAddress()))
            .satisfies(a -> assertThat(a.getCurrentWard()).as("check currentWard").isEqualTo(expected.getCurrentWard()))
            .satisfies(a -> assertThat(a.getCurrentDistrict()).as("check currentDistrict").isEqualTo(expected.getCurrentDistrict()))
            .satisfies(a -> assertThat(a.getCurrentProvince()).as("check currentProvince").isEqualTo(expected.getCurrentProvince()))
            .satisfies(a -> assertThat(a.getLandlinePhone()).as("check landlinePhone").isEqualTo(expected.getLandlinePhone()))
            .satisfies(a -> assertThat(a.getMobilePhone()).as("check mobilePhone").isEqualTo(expected.getMobilePhone()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getMotherName()).as("check motherName").isEqualTo(expected.getMotherName()))
            .satisfies(a -> assertThat(a.getFatherName()).as("check fatherName").isEqualTo(expected.getFatherName()))
            .satisfies(a -> assertThat(a.getCaregiverName()).as("check caregiverName").isEqualTo(expected.getCaregiverName()))
            .satisfies(a -> assertThat(a.getCaregiverRelation()).as("check caregiverRelation").isEqualTo(expected.getCaregiverRelation()))
            .satisfies(a ->
                assertThat(a.getCaregiverLandlinePhone()).as("check caregiverLandlinePhone").isEqualTo(expected.getCaregiverLandlinePhone())
            )
            .satisfies(a ->
                assertThat(a.getCaregiverMobilePhone()).as("check caregiverMobilePhone").isEqualTo(expected.getCaregiverMobilePhone())
            )
            .satisfies(a -> assertThat(a.getFamilyCode()).as("check familyCode").isEqualTo(expected.getFamilyCode()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPatientUpdatableRelationshipsEquals(Patient expected, Patient actual) {
        assertThat(actual)
            .as("Verify Patient relationships")
            .satisfies(a -> assertThat(a.getAdditionalInfo()).as("check additionalInfo").isEqualTo(expected.getAdditionalInfo()))
            .satisfies(a ->
                assertThat(a.getVaccinationsForBaby()).as("check vaccinationsForBaby").isEqualTo(expected.getVaccinationsForBaby())
            );
    }
}
