package com.mycompany.microservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PregnancyTetanusAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPregnancyTetanusAllPropertiesEquals(PregnancyTetanus expected, PregnancyTetanus actual) {
        assertPregnancyTetanusAutoGeneratedPropertiesEquals(expected, actual);
        assertPregnancyTetanusAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPregnancyTetanusAllUpdatablePropertiesEquals(PregnancyTetanus expected, PregnancyTetanus actual) {
        assertPregnancyTetanusUpdatableFieldsEquals(expected, actual);
        assertPregnancyTetanusUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPregnancyTetanusAutoGeneratedPropertiesEquals(PregnancyTetanus expected, PregnancyTetanus actual) {
        assertThat(actual)
            .as("Verify PregnancyTetanus auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPregnancyTetanusUpdatableFieldsEquals(PregnancyTetanus expected, PregnancyTetanus actual) {
        assertThat(actual)
            .as("Verify PregnancyTetanus relevant properties")
            .satisfies(a -> assertThat(a.getDose()).as("check dose").isEqualTo(expected.getDose()))
            .satisfies(a -> assertThat(a.getNotInjected()).as("check notInjected").isEqualTo(expected.getNotInjected()))
            .satisfies(a -> assertThat(a.getInjectionDate()).as("check injectionDate").isEqualTo(expected.getInjectionDate()))
            .satisfies(a -> assertThat(a.getPregnancyMonth()).as("check pregnancyMonth").isEqualTo(expected.getPregnancyMonth()))
            .satisfies(a -> assertThat(a.getReaction()).as("check reaction").isEqualTo(expected.getReaction()))
            .satisfies(a -> assertThat(a.getNextAppointment()).as("check nextAppointment").isEqualTo(expected.getNextAppointment()))
            .satisfies(a ->
                assertThat(a.getNumberOfDosesReceived()).as("check numberOfDosesReceived").isEqualTo(expected.getNumberOfDosesReceived())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPregnancyTetanusUpdatableRelationshipsEquals(PregnancyTetanus expected, PregnancyTetanus actual) {
        assertThat(actual)
            .as("Verify PregnancyTetanus relationships")
            .satisfies(a -> assertThat(a.getPatient()).as("check patient").isEqualTo(expected.getPatient()));
    }
}
