package com.mycompany.microservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SurgeryHistoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSurgeryHistoryAllPropertiesEquals(SurgeryHistory expected, SurgeryHistory actual) {
        assertSurgeryHistoryAutoGeneratedPropertiesEquals(expected, actual);
        assertSurgeryHistoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSurgeryHistoryAllUpdatablePropertiesEquals(SurgeryHistory expected, SurgeryHistory actual) {
        assertSurgeryHistoryUpdatableFieldsEquals(expected, actual);
        assertSurgeryHistoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSurgeryHistoryAutoGeneratedPropertiesEquals(SurgeryHistory expected, SurgeryHistory actual) {
        assertThat(actual)
            .as("Verify SurgeryHistory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSurgeryHistoryUpdatableFieldsEquals(SurgeryHistory expected, SurgeryHistory actual) {
        assertThat(actual)
            .as("Verify SurgeryHistory relevant properties")
            .satisfies(a -> assertThat(a.getBodyPart()).as("check bodyPart").isEqualTo(expected.getBodyPart()))
            .satisfies(a -> assertThat(a.getSurgeryYear()).as("check surgeryYear").isEqualTo(expected.getSurgeryYear()))
            .satisfies(a -> assertThat(a.getNote()).as("check note").isEqualTo(expected.getNote()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSurgeryHistoryUpdatableRelationshipsEquals(SurgeryHistory expected, SurgeryHistory actual) {
        assertThat(actual)
            .as("Verify SurgeryHistory relationships")
            .satisfies(a -> assertThat(a.getPatient()).as("check patient").isEqualTo(expected.getPatient()));
    }
}
