package com.mycompany.microservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VaccinationForBabyAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVaccinationForBabyAllPropertiesEquals(VaccinationForBaby expected, VaccinationForBaby actual) {
        assertVaccinationForBabyAutoGeneratedPropertiesEquals(expected, actual);
        assertVaccinationForBabyAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVaccinationForBabyAllUpdatablePropertiesEquals(VaccinationForBaby expected, VaccinationForBaby actual) {
        assertVaccinationForBabyUpdatableFieldsEquals(expected, actual);
        assertVaccinationForBabyUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVaccinationForBabyAutoGeneratedPropertiesEquals(VaccinationForBaby expected, VaccinationForBaby actual) {
        assertThat(actual)
            .as("Verify VaccinationForBaby auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVaccinationForBabyUpdatableFieldsEquals(VaccinationForBaby expected, VaccinationForBaby actual) {
        assertThat(actual)
            .as("Verify VaccinationForBaby relevant properties")
            .satisfies(a -> assertThat(a.getVaccine()).as("check vaccine").isEqualTo(expected.getVaccine()))
            .satisfies(a -> assertThat(a.getNumberUse()).as("check numberUse").isEqualTo(expected.getNumberUse()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVaccinationForBabyUpdatableRelationshipsEquals(VaccinationForBaby expected, VaccinationForBaby actual) {
        // empty method
    }
}
