package com.mycompany.microservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VaccineAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVaccineAllPropertiesEquals(Vaccine expected, Vaccine actual) {
        assertVaccineAutoGeneratedPropertiesEquals(expected, actual);
        assertVaccineAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVaccineAllUpdatablePropertiesEquals(Vaccine expected, Vaccine actual) {
        assertVaccineUpdatableFieldsEquals(expected, actual);
        assertVaccineUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVaccineAutoGeneratedPropertiesEquals(Vaccine expected, Vaccine actual) {
        assertThat(actual)
            .as("Verify Vaccine auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVaccineUpdatableFieldsEquals(Vaccine expected, Vaccine actual) {
        assertThat(actual)
            .as("Verify Vaccine relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getNotVaccinated()).as("check notVaccinated").isEqualTo(expected.getNotVaccinated()))
            .satisfies(a -> assertThat(a.getInjectionDate()).as("check injectionDate").isEqualTo(expected.getInjectionDate()))
            .satisfies(a -> assertThat(a.getReaction()).as("check reaction").isEqualTo(expected.getReaction()))
            .satisfies(a -> assertThat(a.getNextAppointment()).as("check nextAppointment").isEqualTo(expected.getNextAppointment()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVaccineUpdatableRelationshipsEquals(Vaccine expected, Vaccine actual) {
        assertThat(actual)
            .as("Verify Vaccine relationships")
            .satisfies(a -> assertThat(a.getVaccinationForBaby()).as("check vaccinationForBaby").isEqualTo(expected.getVaccinationForBaby())
            );
    }
}
