package com.mycompany.microservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VaccinationTCMRAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVaccinationTCMRAllPropertiesEquals(VaccinationTCMR expected, VaccinationTCMR actual) {
        assertVaccinationTCMRAutoGeneratedPropertiesEquals(expected, actual);
        assertVaccinationTCMRAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVaccinationTCMRAllUpdatablePropertiesEquals(VaccinationTCMR expected, VaccinationTCMR actual) {
        assertVaccinationTCMRUpdatableFieldsEquals(expected, actual);
        assertVaccinationTCMRUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVaccinationTCMRAutoGeneratedPropertiesEquals(VaccinationTCMR expected, VaccinationTCMR actual) {
        assertThat(actual)
            .as("Verify VaccinationTCMR auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVaccinationTCMRUpdatableFieldsEquals(VaccinationTCMR expected, VaccinationTCMR actual) {
        assertThat(actual)
            .as("Verify VaccinationTCMR relevant properties")
            .satisfies(a -> assertThat(a.getVaccine()).as("check vaccine").isEqualTo(expected.getVaccine()))
            .satisfies(a -> assertThat(a.getNotVaccinated()).as("check notVaccinated").isEqualTo(expected.getNotVaccinated()))
            .satisfies(a -> assertThat(a.getVaccinated()).as("check vaccinated").isEqualTo(expected.getVaccinated()))
            .satisfies(a -> assertThat(a.getInjectionDate()).as("check injectionDate").isEqualTo(expected.getInjectionDate()))
            .satisfies(a -> assertThat(a.getReaction()).as("check reaction").isEqualTo(expected.getReaction()))
            .satisfies(a -> assertThat(a.getNextAppointment()).as("check nextAppointment").isEqualTo(expected.getNextAppointment()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVaccinationTCMRUpdatableRelationshipsEquals(VaccinationTCMR expected, VaccinationTCMR actual) {
        assertThat(actual)
            .as("Verify VaccinationTCMR relationships")
            .satisfies(a -> assertThat(a.getPatient()).as("check patient").isEqualTo(expected.getPatient()));
    }
}
